export type Country = {
  id: string,
    currency: string,
      continent: string | string[],
        AR: string,
          BG: string,
            BR: string,
              CA: string,
                CN: string,
                  CS: string,
                    DA: string,
                      DE: string,
                        EL: string,
                          EN: string,
                            ES: string,
                              FI: string,
                                FR: string,
                                  HR: string,
                                    HU: string,
                                      ID: string,
                                        IE: string,
                                          IS: string,
                                            IT: string,
                                              JA: string,
                                                KO: string,
                                                  LT: string,
                                                    MX: string,
                                                      NL: string,
                                                        NO: string,
                                                          NZ: string,
                                                            PL: string,
                                                              PT: string,
                                                                RO: string,
                                                                  RU: string,
                                                                    SK: string,
                                                                      SR: string,
                                                                        SV: string,
                                                                          TH: string,
                                                                            TR: string,
                                                                              TW: string,
                                                                                UK: string,
                                                                                  VN: string,
                                                                                    HE: string,
};

export type Countries = { [key: string]: Country };

// eslint-disable-next-line import/prefer-default-export
export const countryDefault: Country = {
  id: "gb",
  currency: "gbp",
  continent: "eu",
  AR: "المملكة المتحدة",
  BG: "Обединено кралство",
  BR: "Reino Unido",
  CA: "Regne Unit",
  CN: "英国",
  CS: "Velká Británie",
  DA: "Storbritannien",
  DE: "Vereinigtes Königreich",
  EL: "Ηνωμένο Βασίλειο",
  EN: "United Kingdom",
  ES: "Reino Unido",
  FI: "Britannia",
  FR: "Royaume-Uni",
  HR: "Velika Britanija",
  HU: "Egyesült Királyság",
  ID: "Inggris Raya",
  IE: "United Kingdom",
  IS: "Bretland",
  IT: "Regno Unito",
  JA: "イギリス",
  KO: "영국",
  LT: "Didžioji Britanija",
  MX: "Reino Unido",
  NL: "Verenigd Koninkrijk",
  NO: "Storbritannia",
  NZ: "United Kingdom",
  PL: "Wielka Brytania",
  PT: "Reino Unido",
  RO: "Marea Britanie",
  RU: "Великобритания",
  SK: "Spojené kráľovstvo",
  SR: "Velika Britanija",
  SV: "Storbritannien",
  TH: "สหราชอาณาจักร",
  TR: "Birleşik Krallık",
  TW: "英国",
  UK: "Великобританія",
  VN: "Vương quốc Anh",
  HE: "בריטניה",
};
