// flow-typed signature: 557515a0125740877b288bb6e4f402cd
// flow-typed version: <<STUB>>/@kiwicom/eslint-config-nitro_v^2.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/eslint-config-nitro'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/eslint-config-nitro' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@kiwicom/eslint-config-nitro/index' {
  declare module.exports: $Exports<'@kiwicom/eslint-config-nitro'>;
}
declare module '@kiwicom/eslint-config-nitro/index.js' {
  declare module.exports: $Exports<'@kiwicom/eslint-config-nitro'>;
}
