// flow-typed signature: 48a23db1a5bd0ee36353f1aa7e5fbea8
// flow-typed version: <<STUB>>/@kiwicom/orbit-components_v0.0.0-rc2/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/orbit-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/orbit-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kiwicom/orbit-components/config/build' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/config/enzymeConfig' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/@storybook/react_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-stage-2_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/enzyme_v3.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/enzyme-adapter-react-16_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-config-airbnb_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-config-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/gulp_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/jest_v22.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/jest_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/jest-styled-components_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/raf_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/react-test-renderer_v16.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/rimraf_v2.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/styled-components_v2.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/flow-typed/npm/styled-components_vx.x.x' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Button/IconWrapper' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Button/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/CarrierLogo/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Checkbox/Icon' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Checkbox/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/constants' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Container/Header' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Container/Section' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/FieldFeedback/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Heading/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Icon/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Accomodation' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AccountCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Airplane' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneLanding' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneRight' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirplaneTakeoff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AirportSecurity' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Alert' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/AlertCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/All' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Anywhere' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ArrowDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ArrowUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Atm' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Attachment' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageBig' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageNone' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageRecheck' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Baggages' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BaggageSmall' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BillingDetails' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/BoardingGate' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Bug' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Bus' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Calendar' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CalendarAnytime' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CalendarRange' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CalendarTripLength' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Camera' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Car' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CarRental' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Chat' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Check' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CheckCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronLeft' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronRight' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChevronUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Child' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ChildFriendly' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Circle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/City' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Clock' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Close' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CloseCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Cocktail' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Coffee' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Compass' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ContactEmail' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/CreditCard' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Document' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Download' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Edit' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/EditOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Email' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Entertainment' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Exchange' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Facebook' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Filters' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightDirect' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightMulticity' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightReturn' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FlightServices' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FullScreen' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/FullScreenOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Gallery' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Globe' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Google' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Gps' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/GpsOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Grid' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Gym' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/InformationCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Instagram' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Insurance' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/InsuranceConfirmed' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/InsuranceOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Invoice' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Link' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Linkedin' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/List' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Loading' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Location' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationA' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationAdd' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationB' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationC' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationD' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationE' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationF' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationG' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationH' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationI' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/LocationJ' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Logout' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Lounge' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Map' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Meal' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MenuHamburger' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MenuKebab' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MenuMeatballs' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Messages' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MessagesOutline' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Minus' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MinusCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Money' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/MusicalInstruments' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/NewWindow' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Nonstop' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Notification' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/NotificationOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/NotificationOn' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckin' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckinOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Paid' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Parking' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Passenger' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PassengerAdd' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PassengerOutline' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Passengers' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Passport' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Pet' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Pharmacy' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Phone' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Playground' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Plus' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PlusCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Pool' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PowerPlug' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PowerPlugOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PriorityBoarding' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/PromoCode' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/QuestionCircle' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RadiusSearch' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Relax' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Reload' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Remove' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Replace' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Restaurant' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RouteNoStops' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RouteOneStop' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/RouteTwoStops' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Search' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Seat' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/SelfTransfer' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Send' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Settings' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Share' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShareAndroid' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Shopping' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShowLess' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ShowMore' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sightseeing' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Smoking' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/SmokingOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Spa' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/SportEquipment' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Sports' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/StarEmpty' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/StarFull' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Subway' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Suitcase' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Taxi' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TermsAndConditions' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ThumbDown' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/ThumbUp' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Ticket' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TicketFlight' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TicketOutline' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/TicketTrain' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Timelapse' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Tips' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Toilets' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Train' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Trip' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Twitter' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Visa' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Visibility' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/VisibilityOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Walk' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Wallet' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Wheelchair' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/Wifi' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/icons/WifiOff' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Input/Label' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/InputText/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/InputTextarea/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Radio/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Select/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/SystemMessage/IconWrapper' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/SystemMessage/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/SystemMessage/Message' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/SystemMessage/Title' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Text/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/TextLink/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Theming/ThemedSample' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Theming/ThemeProvider' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Theming/ThemeSwitcher' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/lib/Typography/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Button/__tests__/IconWrapper.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Button/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Button/Button.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Button/IconWrapper' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Button/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/CarrierLogo/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/CarrierLogo/CarrierLogo.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/CarrierLogo/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Checkbox/Checkbox.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Checkbox/Icon' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Checkbox/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/constants' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Container/__tests__/Header.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Container/__tests__/Section.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Container/Header' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Container/Header.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Container/Section' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Container/Section.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/FieldFeedback/__tests__/FieldFeedback.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/FieldFeedback/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Heading/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Heading/Heading.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Heading/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Icon/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Icon/Icon.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Icon/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Input/Label' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/InputText/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/InputText/InputText.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/InputTextarea/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/InputTextarea/InputTextarea.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Radio/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Radio/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Radio/Radio.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Select/__tests__/Select.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Select/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Select/Select.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/__tests__/IconWrapper.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/__tests__/Title.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/IconWrapper' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/Message' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/SystemMessage.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/SystemMessage/Title' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Text/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Text/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Text/Text.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/TextLink/__tests__/index.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/TextLink/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/TextLink/TextLink.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Theming/__tests__/ThemedSample.test' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Theming/ThemedSample' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Theming/ThemeProvider' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Theming/ThemeSwitcher' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Theming/Theming.stories' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Typography/index' {
  declare module.exports: any;
}

declare module '@kiwicom/orbit-components/src/Typography/Typography.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kiwicom/orbit-components/config/build.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/config/build'>;
}
declare module '@kiwicom/orbit-components/config/enzymeConfig.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/config/enzymeConfig'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/@storybook/react_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/@storybook/react_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/babel-preset-stage-2_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/babel-preset-stage-2_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/enzyme_v3.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/enzyme_v3.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/enzyme-adapter-react-16_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/enzyme-adapter-react-16_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-config-airbnb_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-config-airbnb_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-config-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-config-prettier_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-prettier_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/gulp_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/gulp_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/jest_v22.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/jest_v22.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/jest_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/jest_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/jest-styled-components_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/jest-styled-components_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/prettier_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/raf_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/raf_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/react-test-renderer_v16.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/react-test-renderer_v16.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/rimraf_v2.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/rimraf_v2.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/styled-components_v2.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/styled-components_v2.x.x'>;
}
declare module '@kiwicom/orbit-components/flow-typed/npm/styled-components_vx.x.x.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/flow-typed/npm/styled-components_vx.x.x'>;
}
declare module '@kiwicom/orbit-components/lib/Button/IconWrapper.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Button/IconWrapper'>;
}
declare module '@kiwicom/orbit-components/lib/Button/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Button/index'>;
}
declare module '@kiwicom/orbit-components/lib/CarrierLogo/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/CarrierLogo/index'>;
}
declare module '@kiwicom/orbit-components/lib/Checkbox/Icon.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Checkbox/Icon'>;
}
declare module '@kiwicom/orbit-components/lib/Checkbox/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Checkbox/index'>;
}
declare module '@kiwicom/orbit-components/lib/constants.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/constants'>;
}
declare module '@kiwicom/orbit-components/lib/Container/Header.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Container/Header'>;
}
declare module '@kiwicom/orbit-components/lib/Container/Section.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Container/Section'>;
}
declare module '@kiwicom/orbit-components/lib/FieldFeedback/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/FieldFeedback/index'>;
}
declare module '@kiwicom/orbit-components/lib/Heading/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Heading/index'>;
}
declare module '@kiwicom/orbit-components/lib/Icon/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Icon/index'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Accomodation.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Accomodation'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AccountCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AccountCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Airplane.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Airplane'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneLanding.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneLanding'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneRight.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneRight'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirplaneTakeoff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirplaneTakeoff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AirportSecurity.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AirportSecurity'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Alert.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Alert'>;
}
declare module '@kiwicom/orbit-components/lib/icons/AlertCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/AlertCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/All.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/All'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Anywhere.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Anywhere'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ArrowDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ArrowDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ArrowUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ArrowUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Atm.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Atm'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Attachment.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Attachment'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageBig.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageBig'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageNone.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageNone'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageRecheck.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageRecheck'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Baggages.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Baggages'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BaggageSmall.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BaggageSmall'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BillingDetails.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BillingDetails'>;
}
declare module '@kiwicom/orbit-components/lib/icons/BoardingGate.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/BoardingGate'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Bug.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Bug'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Bus.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Bus'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Calendar.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Calendar'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CalendarAnytime.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CalendarAnytime'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CalendarRange.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CalendarRange'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CalendarTripLength.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CalendarTripLength'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Camera.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Camera'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Car.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Car'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CarRental.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CarRental'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Chat.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Chat'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Check.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Check'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CheckCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CheckCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronLeft.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronLeft'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronRight.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronRight'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChevronUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChevronUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Child.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Child'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ChildFriendly.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ChildFriendly'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Circle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Circle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/City.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/City'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Clock.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Clock'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Close.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Close'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CloseCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CloseCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Cocktail.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Cocktail'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Coffee.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Coffee'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Compass.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Compass'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ContactEmail.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ContactEmail'>;
}
declare module '@kiwicom/orbit-components/lib/icons/CreditCard.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/CreditCard'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Document.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Document'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Download.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Download'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Edit.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Edit'>;
}
declare module '@kiwicom/orbit-components/lib/icons/EditOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/EditOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Email.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Email'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Entertainment.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Entertainment'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Exchange.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Exchange'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Facebook.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Facebook'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Filters.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Filters'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightDirect.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightDirect'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightMulticity.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightMulticity'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightReturn.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightReturn'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FlightServices.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FlightServices'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FullScreen.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FullScreen'>;
}
declare module '@kiwicom/orbit-components/lib/icons/FullScreenOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/FullScreenOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Gallery.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Gallery'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Globe.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Globe'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Google.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Google'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Gps.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Gps'>;
}
declare module '@kiwicom/orbit-components/lib/icons/GpsOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/GpsOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Grid.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Grid'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Gym.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Gym'>;
}
declare module '@kiwicom/orbit-components/lib/icons/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/index'>;
}
declare module '@kiwicom/orbit-components/lib/icons/InformationCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/InformationCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Instagram.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Instagram'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Insurance.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Insurance'>;
}
declare module '@kiwicom/orbit-components/lib/icons/InsuranceConfirmed.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/InsuranceConfirmed'>;
}
declare module '@kiwicom/orbit-components/lib/icons/InsuranceOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/InsuranceOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Invoice.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Invoice'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Link.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Link'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Linkedin.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Linkedin'>;
}
declare module '@kiwicom/orbit-components/lib/icons/List.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/List'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Loading.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Loading'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Location.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Location'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationA.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationA'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationAdd.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationAdd'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationB.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationB'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationC.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationC'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationD.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationD'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationE.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationE'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationF.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationF'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationG.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationG'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationH.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationH'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationI.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationI'>;
}
declare module '@kiwicom/orbit-components/lib/icons/LocationJ.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/LocationJ'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Logout.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Logout'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Lounge.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Lounge'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Map.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Map'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Meal.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Meal'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MenuHamburger.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MenuHamburger'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MenuKebab.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MenuKebab'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MenuMeatballs.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MenuMeatballs'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Messages.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Messages'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MessagesOutline.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MessagesOutline'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Minus.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Minus'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MinusCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MinusCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Money.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Money'>;
}
declare module '@kiwicom/orbit-components/lib/icons/MusicalInstruments.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/MusicalInstruments'>;
}
declare module '@kiwicom/orbit-components/lib/icons/NewWindow.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/NewWindow'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Nonstop.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Nonstop'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Notification.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Notification'>;
}
declare module '@kiwicom/orbit-components/lib/icons/NotificationOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/NotificationOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/NotificationOn.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/NotificationOn'>;
}
declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckin.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/OnlineCheckin'>;
}
declare module '@kiwicom/orbit-components/lib/icons/OnlineCheckinOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/OnlineCheckinOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Paid.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Paid'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Parking.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Parking'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Passenger.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Passenger'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PassengerAdd.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PassengerAdd'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PassengerOutline.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PassengerOutline'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Passengers.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Passengers'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Passport.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Passport'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Pet.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Pet'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Pharmacy.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Pharmacy'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Phone.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Phone'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Playground.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Playground'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Plus.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Plus'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PlusCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PlusCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Pool.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Pool'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PowerPlug.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PowerPlug'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PowerPlugOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PowerPlugOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PriorityBoarding.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PriorityBoarding'>;
}
declare module '@kiwicom/orbit-components/lib/icons/PromoCode.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/PromoCode'>;
}
declare module '@kiwicom/orbit-components/lib/icons/QuestionCircle.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/QuestionCircle'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RadiusSearch.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RadiusSearch'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Relax.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Relax'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Reload.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Reload'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Remove.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Remove'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Replace.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Replace'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Restaurant.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Restaurant'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RouteNoStops.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RouteNoStops'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RouteOneStop.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RouteOneStop'>;
}
declare module '@kiwicom/orbit-components/lib/icons/RouteTwoStops.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/RouteTwoStops'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Search.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Search'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Seat.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Seat'>;
}
declare module '@kiwicom/orbit-components/lib/icons/SelfTransfer.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/SelfTransfer'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Send.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Send'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Settings.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Settings'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Share.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Share'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShareAndroid.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShareAndroid'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Shopping.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Shopping'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShowLess.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShowLess'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ShowMore.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ShowMore'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sightseeing.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sightseeing'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Smoking.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Smoking'>;
}
declare module '@kiwicom/orbit-components/lib/icons/SmokingOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/SmokingOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Spa.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Spa'>;
}
declare module '@kiwicom/orbit-components/lib/icons/SportEquipment.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/SportEquipment'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Sports.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Sports'>;
}
declare module '@kiwicom/orbit-components/lib/icons/StarEmpty.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/StarEmpty'>;
}
declare module '@kiwicom/orbit-components/lib/icons/StarFull.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/StarFull'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Subway.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Subway'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Suitcase.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Suitcase'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Taxi.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Taxi'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TermsAndConditions.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TermsAndConditions'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ThumbDown.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ThumbDown'>;
}
declare module '@kiwicom/orbit-components/lib/icons/ThumbUp.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/ThumbUp'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Ticket.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Ticket'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TicketFlight.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TicketFlight'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TicketOutline.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TicketOutline'>;
}
declare module '@kiwicom/orbit-components/lib/icons/TicketTrain.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/TicketTrain'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Timelapse.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Timelapse'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Tips.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Tips'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Toilets.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Toilets'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Train.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Train'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Trip.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Trip'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Twitter.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Twitter'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Visa.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Visa'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Visibility.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Visibility'>;
}
declare module '@kiwicom/orbit-components/lib/icons/VisibilityOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/VisibilityOff'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Walk.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Walk'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Wallet.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Wallet'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Wheelchair.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Wheelchair'>;
}
declare module '@kiwicom/orbit-components/lib/icons/Wifi.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/Wifi'>;
}
declare module '@kiwicom/orbit-components/lib/icons/WifiOff.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/icons/WifiOff'>;
}
declare module '@kiwicom/orbit-components/lib/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/index'>;
}
declare module '@kiwicom/orbit-components/lib/Input/Label.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Input/Label'>;
}
declare module '@kiwicom/orbit-components/lib/InputText/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/InputText/index'>;
}
declare module '@kiwicom/orbit-components/lib/InputTextarea/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/InputTextarea/index'>;
}
declare module '@kiwicom/orbit-components/lib/Radio/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Radio/index'>;
}
declare module '@kiwicom/orbit-components/lib/Select/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Select/index'>;
}
declare module '@kiwicom/orbit-components/lib/SystemMessage/IconWrapper.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/SystemMessage/IconWrapper'>;
}
declare module '@kiwicom/orbit-components/lib/SystemMessage/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/SystemMessage/index'>;
}
declare module '@kiwicom/orbit-components/lib/SystemMessage/Message.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/SystemMessage/Message'>;
}
declare module '@kiwicom/orbit-components/lib/SystemMessage/Title.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/SystemMessage/Title'>;
}
declare module '@kiwicom/orbit-components/lib/Text/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Text/index'>;
}
declare module '@kiwicom/orbit-components/lib/TextLink/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/TextLink/index'>;
}
declare module '@kiwicom/orbit-components/lib/Theming/ThemedSample.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Theming/ThemedSample'>;
}
declare module '@kiwicom/orbit-components/lib/Theming/ThemeProvider.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Theming/ThemeProvider'>;
}
declare module '@kiwicom/orbit-components/lib/Theming/ThemeSwitcher.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Theming/ThemeSwitcher'>;
}
declare module '@kiwicom/orbit-components/lib/Typography/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/lib/Typography/index'>;
}
declare module '@kiwicom/orbit-components/src/Button/__tests__/IconWrapper.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Button/__tests__/IconWrapper.test'>;
}
declare module '@kiwicom/orbit-components/src/Button/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Button/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/Button/Button.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Button/Button.stories'>;
}
declare module '@kiwicom/orbit-components/src/Button/IconWrapper.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Button/IconWrapper'>;
}
declare module '@kiwicom/orbit-components/src/Button/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Button/index'>;
}
declare module '@kiwicom/orbit-components/src/CarrierLogo/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/CarrierLogo/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/CarrierLogo/CarrierLogo.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/CarrierLogo/CarrierLogo.stories'>;
}
declare module '@kiwicom/orbit-components/src/CarrierLogo/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/CarrierLogo/index'>;
}
declare module '@kiwicom/orbit-components/src/Checkbox/Checkbox.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Checkbox/Checkbox.stories'>;
}
declare module '@kiwicom/orbit-components/src/Checkbox/Icon.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Checkbox/Icon'>;
}
declare module '@kiwicom/orbit-components/src/Checkbox/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Checkbox/index'>;
}
declare module '@kiwicom/orbit-components/src/constants.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/constants'>;
}
declare module '@kiwicom/orbit-components/src/Container/__tests__/Header.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Container/__tests__/Header.test'>;
}
declare module '@kiwicom/orbit-components/src/Container/__tests__/Section.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Container/__tests__/Section.test'>;
}
declare module '@kiwicom/orbit-components/src/Container/Header.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Container/Header'>;
}
declare module '@kiwicom/orbit-components/src/Container/Header.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Container/Header.stories'>;
}
declare module '@kiwicom/orbit-components/src/Container/Section.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Container/Section'>;
}
declare module '@kiwicom/orbit-components/src/Container/Section.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Container/Section.stories'>;
}
declare module '@kiwicom/orbit-components/src/FieldFeedback/__tests__/FieldFeedback.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/FieldFeedback/__tests__/FieldFeedback.test'>;
}
declare module '@kiwicom/orbit-components/src/FieldFeedback/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/FieldFeedback/index'>;
}
declare module '@kiwicom/orbit-components/src/Heading/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Heading/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/Heading/Heading.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Heading/Heading.stories'>;
}
declare module '@kiwicom/orbit-components/src/Heading/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Heading/index'>;
}
declare module '@kiwicom/orbit-components/src/Icon/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Icon/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/Icon/Icon.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Icon/Icon.stories'>;
}
declare module '@kiwicom/orbit-components/src/Icon/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Icon/index'>;
}
declare module '@kiwicom/orbit-components/src/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/index'>;
}
declare module '@kiwicom/orbit-components/src/Input/Label.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Input/Label'>;
}
declare module '@kiwicom/orbit-components/src/InputText/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/InputText/index'>;
}
declare module '@kiwicom/orbit-components/src/InputText/InputText.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/InputText/InputText.stories'>;
}
declare module '@kiwicom/orbit-components/src/InputTextarea/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/InputTextarea/index'>;
}
declare module '@kiwicom/orbit-components/src/InputTextarea/InputTextarea.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/InputTextarea/InputTextarea.stories'>;
}
declare module '@kiwicom/orbit-components/src/Radio/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Radio/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/Radio/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Radio/index'>;
}
declare module '@kiwicom/orbit-components/src/Radio/Radio.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Radio/Radio.stories'>;
}
declare module '@kiwicom/orbit-components/src/Select/__tests__/Select.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Select/__tests__/Select.test'>;
}
declare module '@kiwicom/orbit-components/src/Select/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Select/index'>;
}
declare module '@kiwicom/orbit-components/src/Select/Select.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Select/Select.stories'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/__tests__/IconWrapper.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/__tests__/IconWrapper.test'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/__tests__/Title.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/__tests__/Title.test'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/IconWrapper.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/IconWrapper'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/index'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/Message.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/Message'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/SystemMessage.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/SystemMessage.stories'>;
}
declare module '@kiwicom/orbit-components/src/SystemMessage/Title.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/SystemMessage/Title'>;
}
declare module '@kiwicom/orbit-components/src/Text/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Text/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/Text/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Text/index'>;
}
declare module '@kiwicom/orbit-components/src/Text/Text.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Text/Text.stories'>;
}
declare module '@kiwicom/orbit-components/src/TextLink/__tests__/index.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/TextLink/__tests__/index.test'>;
}
declare module '@kiwicom/orbit-components/src/TextLink/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/TextLink/index'>;
}
declare module '@kiwicom/orbit-components/src/TextLink/TextLink.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/TextLink/TextLink.stories'>;
}
declare module '@kiwicom/orbit-components/src/Theming/__tests__/ThemedSample.test.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Theming/__tests__/ThemedSample.test'>;
}
declare module '@kiwicom/orbit-components/src/Theming/ThemedSample.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Theming/ThemedSample'>;
}
declare module '@kiwicom/orbit-components/src/Theming/ThemeProvider.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Theming/ThemeProvider'>;
}
declare module '@kiwicom/orbit-components/src/Theming/ThemeSwitcher.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Theming/ThemeSwitcher'>;
}
declare module '@kiwicom/orbit-components/src/Theming/Theming.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Theming/Theming.stories'>;
}
declare module '@kiwicom/orbit-components/src/Typography/index.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Typography/index'>;
}
declare module '@kiwicom/orbit-components/src/Typography/Typography.stories.js' {
  declare module.exports: $Exports<'@kiwicom/orbit-components/src/Typography/Typography.stories'>;
}
