// flow-typed signature: b1dc49e6afa4f11fce2e6c29369e7ae5
// flow-typed version: <<STUB>>/@kiwicom/relay_v3.1.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kiwicom/relay/bin/kiwicom-relay-compiler' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/commitLocalUpdate' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/commitMutation' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/compiler/__generated__/persistOperationMutation.graphql' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/compiler/buildLanguagePlugin' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/compiler/formatGeneratedModule' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/compiler/index' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/compiler/persistOperation' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/createEnvironment' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/createFragmentContainer' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/createPaginationContainer' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/createRefetchContainer' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/createRequestHandler' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/fetchers/createNetworkFetcher' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/graphql' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/helpers' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/index' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/QueryRenderer' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/requestSubscription' {
  declare module.exports: any;
}

declare module '@kiwicom/relay/src/types.flow' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kiwicom/relay/bin/kiwicom-relay-compiler.js' {
  declare module.exports: $Exports<'@kiwicom/relay/bin/kiwicom-relay-compiler'>;
}
declare module '@kiwicom/relay/src/commitLocalUpdate.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/commitLocalUpdate'>;
}
declare module '@kiwicom/relay/src/commitMutation.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/commitMutation'>;
}
declare module '@kiwicom/relay/src/compiler/__generated__/persistOperationMutation.graphql.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/compiler/__generated__/persistOperationMutation.graphql'>;
}
declare module '@kiwicom/relay/src/compiler/buildLanguagePlugin.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/compiler/buildLanguagePlugin'>;
}
declare module '@kiwicom/relay/src/compiler/formatGeneratedModule.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/compiler/formatGeneratedModule'>;
}
declare module '@kiwicom/relay/src/compiler/index.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/compiler/index'>;
}
declare module '@kiwicom/relay/src/compiler/persistOperation.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/compiler/persistOperation'>;
}
declare module '@kiwicom/relay/src/createEnvironment.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/createEnvironment'>;
}
declare module '@kiwicom/relay/src/createFragmentContainer.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/createFragmentContainer'>;
}
declare module '@kiwicom/relay/src/createPaginationContainer.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/createPaginationContainer'>;
}
declare module '@kiwicom/relay/src/createRefetchContainer.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/createRefetchContainer'>;
}
declare module '@kiwicom/relay/src/createRequestHandler.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/createRequestHandler'>;
}
declare module '@kiwicom/relay/src/fetchers/createNetworkFetcher.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/fetchers/createNetworkFetcher'>;
}
declare module '@kiwicom/relay/src/graphql.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/graphql'>;
}
declare module '@kiwicom/relay/src/helpers.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/helpers'>;
}
declare module '@kiwicom/relay/src/index.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/index'>;
}
declare module '@kiwicom/relay/src/QueryRenderer.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/QueryRenderer'>;
}
declare module '@kiwicom/relay/src/requestSubscription.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/requestSubscription'>;
}
declare module '@kiwicom/relay/src/types.flow.js' {
  declare module.exports: $Exports<'@kiwicom/relay/src/types.flow'>;
}
