// flow-typed signature: ace4713a8c2f1d9b3b6eb7dcb6cf234d
// flow-typed version: <<STUB>>/@kiwicom/translations_v^1.79.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/translations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/translations' {
  declare module.exports: any;
}
