// flow-typed signature: 33801d92b7f9ef3c12e0ac95bfd8eeb8
// flow-typed version: <<STUB>>/@kiwicom/translations_v^1.46.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/translations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/translations' {
  declare module.exports: any;
}
