// flow-typed signature: e8b49989c6e29d2e1af2f93f904e5e43
// flow-typed version: <<STUB>>/babel-plugin-idx_v^2.4.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-idx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-idx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-idx/lib/babel-plugin-idx' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-idx/lib/babel-plugin-idx.js' {
  declare module.exports: $Exports<'babel-plugin-idx/lib/babel-plugin-idx'>;
}
