// flow-typed signature: 8cfb849babc74c52c96f7e869a1f1a02
// flow-typed version: <<STUB>>/babel-plugin-id_v^1.0.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-id'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-id' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-id/index' {
  declare module.exports: $Exports<'babel-plugin-id'>;
}
declare module 'babel-plugin-id/index.js' {
  declare module.exports: $Exports<'babel-plugin-id'>;
}
