// flow-typed signature: ecd9f06c072278b479ea8ad6a59a9ae5
// flow-typed version: <<STUB>>/decimal.js_v10.1.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decimal.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decimal.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'decimal.js/decimal' {
  declare module.exports: any;
}

declare module 'decimal.js/decimal.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'decimal.js/decimal.js' {
  declare module.exports: $Exports<'decimal.js/decimal'>;
}
declare module 'decimal.js/decimal.min.js' {
  declare module.exports: $Exports<'decimal.js/decimal.min'>;
}
