// flow-typed signature: 747876497f76460bebc80f7d2377d2ec
// flow-typed version: <<STUB>>/i18n-extract_v^0.5.1/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n-extract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n-extract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n-extract/examples/polyglot' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCode' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCode.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/comment' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/disable-comment' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/duplicated' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/dynamicConcat' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/dynamicImport' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/dynamicTemplate' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/es5' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/es6' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/function' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/many-args' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/marker' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/markerComposed' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/memberExpression' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCodeFixtures/template' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFiles' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFiles.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFilesFixture/AccoutView' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFilesFixture/ExpenseView' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFilesFixture/MemberView' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findDuplicated' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findDuplicated.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findMissing' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findMissing.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findUnused' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findUnused.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/flatten' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/flatten.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/forbidDynamic' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/forbidDynamic.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/index' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/mergeMessagesWithPO' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/mergeMessagesWithPO.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/mergeMessagesWithPOFixtures/input' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/utils' {
  declare module.exports: any;
}

declare module 'i18n-extract/prettier.config' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCode' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCode.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/comment' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/disable-comment' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/duplicated' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/dynamicConcat' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/dynamicImport' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/dynamicTemplate' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/es5' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/es6' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/function' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/many-args' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/marker' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/markerComposed' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/memberExpression' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCodeFixtures/template' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFiles' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFiles.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFilesFixture/AccoutView' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFilesFixture/ExpenseView' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFilesFixture/MemberView' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findDuplicated' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findDuplicated.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findMissing' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findMissing.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findUnused' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findUnused.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/flatten' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/flatten.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/forbidDynamic' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/forbidDynamic.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/index' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/mergeMessagesWithPO' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/mergeMessagesWithPO.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/mergeMessagesWithPOFixtures/input' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n-extract/examples/polyglot.js' {
  declare module.exports: $Exports<'i18n-extract/examples/polyglot'>;
}
declare module 'i18n-extract/lib/extractFromCode.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCode'>;
}
declare module 'i18n-extract/lib/extractFromCode.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCode.spec'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/comment.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/comment'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/disable-comment.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/disable-comment'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/duplicated.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/duplicated'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/dynamicConcat.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/dynamicConcat'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/dynamicImport.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/dynamicImport'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/dynamicTemplate.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/dynamicTemplate'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/es5.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/es5'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/es6.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/es6'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/function.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/function'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/many-args.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/many-args'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/marker.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/marker'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/markerComposed.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/markerComposed'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/memberExpression.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/memberExpression'>;
}
declare module 'i18n-extract/lib/extractFromCodeFixtures/template.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCodeFixtures/template'>;
}
declare module 'i18n-extract/lib/extractFromFiles.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFiles'>;
}
declare module 'i18n-extract/lib/extractFromFiles.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFiles.spec'>;
}
declare module 'i18n-extract/lib/extractFromFilesFixture/AccoutView.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFilesFixture/AccoutView'>;
}
declare module 'i18n-extract/lib/extractFromFilesFixture/ExpenseView.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFilesFixture/ExpenseView'>;
}
declare module 'i18n-extract/lib/extractFromFilesFixture/MemberView.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFilesFixture/MemberView'>;
}
declare module 'i18n-extract/lib/findDuplicated.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findDuplicated'>;
}
declare module 'i18n-extract/lib/findDuplicated.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findDuplicated.spec'>;
}
declare module 'i18n-extract/lib/findMissing.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findMissing'>;
}
declare module 'i18n-extract/lib/findMissing.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findMissing.spec'>;
}
declare module 'i18n-extract/lib/findUnused.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findUnused'>;
}
declare module 'i18n-extract/lib/findUnused.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findUnused.spec'>;
}
declare module 'i18n-extract/lib/flatten.js' {
  declare module.exports: $Exports<'i18n-extract/lib/flatten'>;
}
declare module 'i18n-extract/lib/flatten.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/flatten.spec'>;
}
declare module 'i18n-extract/lib/forbidDynamic.js' {
  declare module.exports: $Exports<'i18n-extract/lib/forbidDynamic'>;
}
declare module 'i18n-extract/lib/forbidDynamic.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/forbidDynamic.spec'>;
}
declare module 'i18n-extract/lib/index.js' {
  declare module.exports: $Exports<'i18n-extract/lib/index'>;
}
declare module 'i18n-extract/lib/mergeMessagesWithPO.js' {
  declare module.exports: $Exports<'i18n-extract/lib/mergeMessagesWithPO'>;
}
declare module 'i18n-extract/lib/mergeMessagesWithPO.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/mergeMessagesWithPO.spec'>;
}
declare module 'i18n-extract/lib/mergeMessagesWithPOFixtures/input.js' {
  declare module.exports: $Exports<'i18n-extract/lib/mergeMessagesWithPOFixtures/input'>;
}
declare module 'i18n-extract/lib/utils.js' {
  declare module.exports: $Exports<'i18n-extract/lib/utils'>;
}
declare module 'i18n-extract/prettier.config.js' {
  declare module.exports: $Exports<'i18n-extract/prettier.config'>;
}
declare module 'i18n-extract/src/extractFromCode.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCode'>;
}
declare module 'i18n-extract/src/extractFromCode.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCode.spec'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/comment.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/comment'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/disable-comment.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/disable-comment'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/duplicated.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/duplicated'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/dynamicConcat.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/dynamicConcat'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/dynamicImport.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/dynamicImport'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/dynamicTemplate.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/dynamicTemplate'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/es5.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/es5'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/es6.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/es6'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/function.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/function'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/many-args.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/many-args'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/marker.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/marker'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/markerComposed.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/markerComposed'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/memberExpression.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/memberExpression'>;
}
declare module 'i18n-extract/src/extractFromCodeFixtures/template.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCodeFixtures/template'>;
}
declare module 'i18n-extract/src/extractFromFiles.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFiles'>;
}
declare module 'i18n-extract/src/extractFromFiles.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFiles.spec'>;
}
declare module 'i18n-extract/src/extractFromFilesFixture/AccoutView.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFilesFixture/AccoutView'>;
}
declare module 'i18n-extract/src/extractFromFilesFixture/ExpenseView.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFilesFixture/ExpenseView'>;
}
declare module 'i18n-extract/src/extractFromFilesFixture/MemberView.jsx' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFilesFixture/MemberView'>;
}
declare module 'i18n-extract/src/findDuplicated.js' {
  declare module.exports: $Exports<'i18n-extract/src/findDuplicated'>;
}
declare module 'i18n-extract/src/findDuplicated.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/findDuplicated.spec'>;
}
declare module 'i18n-extract/src/findMissing.js' {
  declare module.exports: $Exports<'i18n-extract/src/findMissing'>;
}
declare module 'i18n-extract/src/findMissing.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/findMissing.spec'>;
}
declare module 'i18n-extract/src/findUnused.js' {
  declare module.exports: $Exports<'i18n-extract/src/findUnused'>;
}
declare module 'i18n-extract/src/findUnused.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/findUnused.spec'>;
}
declare module 'i18n-extract/src/flatten.js' {
  declare module.exports: $Exports<'i18n-extract/src/flatten'>;
}
declare module 'i18n-extract/src/flatten.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/flatten.spec'>;
}
declare module 'i18n-extract/src/forbidDynamic.js' {
  declare module.exports: $Exports<'i18n-extract/src/forbidDynamic'>;
}
declare module 'i18n-extract/src/forbidDynamic.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/forbidDynamic.spec'>;
}
declare module 'i18n-extract/src/index.js' {
  declare module.exports: $Exports<'i18n-extract/src/index'>;
}
declare module 'i18n-extract/src/mergeMessagesWithPO.js' {
  declare module.exports: $Exports<'i18n-extract/src/mergeMessagesWithPO'>;
}
declare module 'i18n-extract/src/mergeMessagesWithPO.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/mergeMessagesWithPO.spec'>;
}
declare module 'i18n-extract/src/mergeMessagesWithPOFixtures/input.js' {
  declare module.exports: $Exports<'i18n-extract/src/mergeMessagesWithPOFixtures/input'>;
}
declare module 'i18n-extract/src/utils.js' {
  declare module.exports: $Exports<'i18n-extract/src/utils'>;
}
