// flow-typed signature: af032249d83eb4634773f4f0d08bb36f
// flow-typed version: <<STUB>>/i18n-extract_v^0.6.3/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18n-extract'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18n-extract' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18n-extract/lib/extractFromCode' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromCode.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFiles' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/extractFromFiles.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findDuplicated' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findDuplicated.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findMissing' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findMissing.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findUnused' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/findUnused.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/flatten' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/flatten.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/forbidDynamic' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/forbidDynamic.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/index' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/mergeMessagesWithPO' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/mergeMessagesWithPO.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/lib/utils' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCode' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromCode.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFiles' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/extractFromFiles.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findDuplicated' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findDuplicated.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findMissing' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findMissing.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findUnused' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/findUnused.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/flatten' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/flatten.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/forbidDynamic' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/forbidDynamic.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/index' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/mergeMessagesWithPO' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/mergeMessagesWithPO.spec' {
  declare module.exports: any;
}

declare module 'i18n-extract/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18n-extract/lib/extractFromCode.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCode'>;
}
declare module 'i18n-extract/lib/extractFromCode.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromCode.spec'>;
}
declare module 'i18n-extract/lib/extractFromFiles.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFiles'>;
}
declare module 'i18n-extract/lib/extractFromFiles.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/extractFromFiles.spec'>;
}
declare module 'i18n-extract/lib/findDuplicated.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findDuplicated'>;
}
declare module 'i18n-extract/lib/findDuplicated.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findDuplicated.spec'>;
}
declare module 'i18n-extract/lib/findMissing.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findMissing'>;
}
declare module 'i18n-extract/lib/findMissing.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findMissing.spec'>;
}
declare module 'i18n-extract/lib/findUnused.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findUnused'>;
}
declare module 'i18n-extract/lib/findUnused.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/findUnused.spec'>;
}
declare module 'i18n-extract/lib/flatten.js' {
  declare module.exports: $Exports<'i18n-extract/lib/flatten'>;
}
declare module 'i18n-extract/lib/flatten.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/flatten.spec'>;
}
declare module 'i18n-extract/lib/forbidDynamic.js' {
  declare module.exports: $Exports<'i18n-extract/lib/forbidDynamic'>;
}
declare module 'i18n-extract/lib/forbidDynamic.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/forbidDynamic.spec'>;
}
declare module 'i18n-extract/lib/index.js' {
  declare module.exports: $Exports<'i18n-extract/lib/index'>;
}
declare module 'i18n-extract/lib/mergeMessagesWithPO.js' {
  declare module.exports: $Exports<'i18n-extract/lib/mergeMessagesWithPO'>;
}
declare module 'i18n-extract/lib/mergeMessagesWithPO.spec.js' {
  declare module.exports: $Exports<'i18n-extract/lib/mergeMessagesWithPO.spec'>;
}
declare module 'i18n-extract/lib/utils.js' {
  declare module.exports: $Exports<'i18n-extract/lib/utils'>;
}
declare module 'i18n-extract/src/extractFromCode.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCode'>;
}
declare module 'i18n-extract/src/extractFromCode.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromCode.spec'>;
}
declare module 'i18n-extract/src/extractFromFiles.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFiles'>;
}
declare module 'i18n-extract/src/extractFromFiles.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/extractFromFiles.spec'>;
}
declare module 'i18n-extract/src/findDuplicated.js' {
  declare module.exports: $Exports<'i18n-extract/src/findDuplicated'>;
}
declare module 'i18n-extract/src/findDuplicated.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/findDuplicated.spec'>;
}
declare module 'i18n-extract/src/findMissing.js' {
  declare module.exports: $Exports<'i18n-extract/src/findMissing'>;
}
declare module 'i18n-extract/src/findMissing.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/findMissing.spec'>;
}
declare module 'i18n-extract/src/findUnused.js' {
  declare module.exports: $Exports<'i18n-extract/src/findUnused'>;
}
declare module 'i18n-extract/src/findUnused.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/findUnused.spec'>;
}
declare module 'i18n-extract/src/flatten.js' {
  declare module.exports: $Exports<'i18n-extract/src/flatten'>;
}
declare module 'i18n-extract/src/flatten.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/flatten.spec'>;
}
declare module 'i18n-extract/src/forbidDynamic.js' {
  declare module.exports: $Exports<'i18n-extract/src/forbidDynamic'>;
}
declare module 'i18n-extract/src/forbidDynamic.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/forbidDynamic.spec'>;
}
declare module 'i18n-extract/src/index.js' {
  declare module.exports: $Exports<'i18n-extract/src/index'>;
}
declare module 'i18n-extract/src/mergeMessagesWithPO.js' {
  declare module.exports: $Exports<'i18n-extract/src/mergeMessagesWithPO'>;
}
declare module 'i18n-extract/src/mergeMessagesWithPO.spec.js' {
  declare module.exports: $Exports<'i18n-extract/src/mergeMessagesWithPO.spec'>;
}
declare module 'i18n-extract/src/utils.js' {
  declare module.exports: $Exports<'i18n-extract/src/utils'>;
}
