// flow-typed signature: 69e120740f074f8bf09272e062c9d5ac
// flow-typed version: <<STUB>>/libphonenumber-js_v^1.6.4/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'libphonenumber-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'libphonenumber-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'libphonenumber-js/bin/update-metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/AsYouType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/isValidCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/isValidPreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/Leniency' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/parsePreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/utf-8' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findNumbers/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/findPhoneNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/formatIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/formatNumberForMobileDialing' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getCountryCallingCode' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getExampleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/getNumberType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/IDD' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isPossibleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/isValidNumberForRegion' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parseIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/parsePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/PhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/PhoneNumberMatcher' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/RFC3966' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/searchNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/build/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/bundle/libphonenumber-js.min' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/custom' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/AsYouType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/isValidCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/isValidPreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/Leniency' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/parsePreCandidate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/utf-8' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findNumbers/util' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/findPhoneNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/format' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/formatIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/formatNumberForMobileDialing' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getCountryCallingCode' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getExampleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/getNumberType' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/IDD' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isPossibleNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/isValidNumberForRegion' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/metadata' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parse' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parseIncompletePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/parsePhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/PhoneNumber' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/PhoneNumberMatcher' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/RFC3966' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/searchNumbers' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/compress' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/tools/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/es6/validate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/index.common' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/index.es6' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/download' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/generate' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-branch' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-update-and-push-and-pull-request' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-update-and-push' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/metadata-update-and-release' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/modules/commit' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/modules/exec' {
  declare module.exports: any;
}

declare module 'libphonenumber-js/runnable/modules/update-metadata' {
  declare module.exports: any;
}

// Filename aliases
declare module 'libphonenumber-js/bin/update-metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/bin/update-metadata'>;
}
declare module 'libphonenumber-js/build/AsYouType.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/AsYouType'>;
}
declare module 'libphonenumber-js/build/common.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/common'>;
}
declare module 'libphonenumber-js/build/findNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers'>;
}
declare module 'libphonenumber-js/build/findNumbers/isValidCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/isValidCandidate'>;
}
declare module 'libphonenumber-js/build/findNumbers/isValidPreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/isValidPreCandidate'>;
}
declare module 'libphonenumber-js/build/findNumbers/Leniency.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/Leniency'>;
}
declare module 'libphonenumber-js/build/findNumbers/parsePreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/parsePreCandidate'>;
}
declare module 'libphonenumber-js/build/findNumbers/utf-8.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/utf-8'>;
}
declare module 'libphonenumber-js/build/findNumbers/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findNumbers/util'>;
}
declare module 'libphonenumber-js/build/findPhoneNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/findPhoneNumbers'>;
}
declare module 'libphonenumber-js/build/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/format'>;
}
declare module 'libphonenumber-js/build/formatIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/formatIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/build/formatNumberForMobileDialing.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/formatNumberForMobileDialing'>;
}
declare module 'libphonenumber-js/build/getCountryCallingCode.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getCountryCallingCode'>;
}
declare module 'libphonenumber-js/build/getExampleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getExampleNumber'>;
}
declare module 'libphonenumber-js/build/getNumberType.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/getNumberType'>;
}
declare module 'libphonenumber-js/build/IDD.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/IDD'>;
}
declare module 'libphonenumber-js/build/isPossibleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isPossibleNumber'>;
}
declare module 'libphonenumber-js/build/isValidNumberForRegion.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/isValidNumberForRegion'>;
}
declare module 'libphonenumber-js/build/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/metadata'>;
}
declare module 'libphonenumber-js/build/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parse'>;
}
declare module 'libphonenumber-js/build/parseIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parseIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/build/parsePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/parsePhoneNumber'>;
}
declare module 'libphonenumber-js/build/PhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/PhoneNumber'>;
}
declare module 'libphonenumber-js/build/PhoneNumberMatcher.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/PhoneNumberMatcher'>;
}
declare module 'libphonenumber-js/build/RFC3966.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/RFC3966'>;
}
declare module 'libphonenumber-js/build/searchNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/searchNumbers'>;
}
declare module 'libphonenumber-js/build/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/compress'>;
}
declare module 'libphonenumber-js/build/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/download'>;
}
declare module 'libphonenumber-js/build/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/tools/generate'>;
}
declare module 'libphonenumber-js/build/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/build/validate'>;
}
declare module 'libphonenumber-js/bundle/libphonenumber-js.min.js' {
  declare module.exports: $Exports<'libphonenumber-js/bundle/libphonenumber-js.min'>;
}
declare module 'libphonenumber-js/custom.js' {
  declare module.exports: $Exports<'libphonenumber-js/custom'>;
}
declare module 'libphonenumber-js/es6/AsYouType.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/AsYouType'>;
}
declare module 'libphonenumber-js/es6/common.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/common'>;
}
declare module 'libphonenumber-js/es6/findNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers'>;
}
declare module 'libphonenumber-js/es6/findNumbers/isValidCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/isValidCandidate'>;
}
declare module 'libphonenumber-js/es6/findNumbers/isValidPreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/isValidPreCandidate'>;
}
declare module 'libphonenumber-js/es6/findNumbers/Leniency.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/Leniency'>;
}
declare module 'libphonenumber-js/es6/findNumbers/parsePreCandidate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/parsePreCandidate'>;
}
declare module 'libphonenumber-js/es6/findNumbers/utf-8.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/utf-8'>;
}
declare module 'libphonenumber-js/es6/findNumbers/util.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findNumbers/util'>;
}
declare module 'libphonenumber-js/es6/findPhoneNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/findPhoneNumbers'>;
}
declare module 'libphonenumber-js/es6/format.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/format'>;
}
declare module 'libphonenumber-js/es6/formatIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/formatIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/formatNumberForMobileDialing.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/formatNumberForMobileDialing'>;
}
declare module 'libphonenumber-js/es6/getCountryCallingCode.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getCountryCallingCode'>;
}
declare module 'libphonenumber-js/es6/getExampleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getExampleNumber'>;
}
declare module 'libphonenumber-js/es6/getNumberType.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/getNumberType'>;
}
declare module 'libphonenumber-js/es6/IDD.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/IDD'>;
}
declare module 'libphonenumber-js/es6/isPossibleNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isPossibleNumber'>;
}
declare module 'libphonenumber-js/es6/isValidNumberForRegion.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/isValidNumberForRegion'>;
}
declare module 'libphonenumber-js/es6/metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/metadata'>;
}
declare module 'libphonenumber-js/es6/parse.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parse'>;
}
declare module 'libphonenumber-js/es6/parseIncompletePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parseIncompletePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/parsePhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/parsePhoneNumber'>;
}
declare module 'libphonenumber-js/es6/PhoneNumber.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/PhoneNumber'>;
}
declare module 'libphonenumber-js/es6/PhoneNumberMatcher.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/PhoneNumberMatcher'>;
}
declare module 'libphonenumber-js/es6/RFC3966.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/RFC3966'>;
}
declare module 'libphonenumber-js/es6/searchNumbers.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/searchNumbers'>;
}
declare module 'libphonenumber-js/es6/tools/compress.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/compress'>;
}
declare module 'libphonenumber-js/es6/tools/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/download'>;
}
declare module 'libphonenumber-js/es6/tools/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/tools/generate'>;
}
declare module 'libphonenumber-js/es6/validate.js' {
  declare module.exports: $Exports<'libphonenumber-js/es6/validate'>;
}
declare module 'libphonenumber-js/index.common.js' {
  declare module.exports: $Exports<'libphonenumber-js/index.common'>;
}
declare module 'libphonenumber-js/index.es6.js' {
  declare module.exports: $Exports<'libphonenumber-js/index.es6'>;
}
declare module 'libphonenumber-js/runnable/download.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/download'>;
}
declare module 'libphonenumber-js/runnable/generate.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/generate'>;
}
declare module 'libphonenumber-js/runnable/metadata-branch.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-branch'>;
}
declare module 'libphonenumber-js/runnable/metadata-update-and-push-and-pull-request.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-update-and-push-and-pull-request'>;
}
declare module 'libphonenumber-js/runnable/metadata-update-and-push.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-update-and-push'>;
}
declare module 'libphonenumber-js/runnable/metadata-update-and-release.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/metadata-update-and-release'>;
}
declare module 'libphonenumber-js/runnable/modules/commit.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/modules/commit'>;
}
declare module 'libphonenumber-js/runnable/modules/exec.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/modules/exec'>;
}
declare module 'libphonenumber-js/runnable/modules/update-metadata.js' {
  declare module.exports: $Exports<'libphonenumber-js/runnable/modules/update-metadata'>;
}
