// flow-typed signature: 3b0f77783aad4d8963de071834e83d90
// flow-typed version: <<STUB>>/relay-test-utils_v5.0.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'relay-test-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'relay-test-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'relay-test-utils/lib/getOutputForFixture' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/index' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/parseGraphQLText' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/RelayMockPayloadGenerator' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/RelayModernMockEnvironment' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/RelayModernTestUtils' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/RelayTestSchema' {
  declare module.exports: any;
}

declare module 'relay-test-utils/lib/RelayTestSchemaPath' {
  declare module.exports: any;
}

declare module 'relay-test-utils/relay-test-utils' {
  declare module.exports: any;
}

declare module 'relay-test-utils/relay-test-utils.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'relay-test-utils/index' {
  declare module.exports: $Exports<'relay-test-utils'>;
}
declare module 'relay-test-utils/index.js' {
  declare module.exports: $Exports<'relay-test-utils'>;
}
declare module 'relay-test-utils/lib/getOutputForFixture.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/getOutputForFixture'>;
}
declare module 'relay-test-utils/lib/index.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/index'>;
}
declare module 'relay-test-utils/lib/parseGraphQLText.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/parseGraphQLText'>;
}
declare module 'relay-test-utils/lib/RelayMockPayloadGenerator.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/RelayMockPayloadGenerator'>;
}
declare module 'relay-test-utils/lib/RelayModernMockEnvironment.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/RelayModernMockEnvironment'>;
}
declare module 'relay-test-utils/lib/RelayModernTestUtils.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/RelayModernTestUtils'>;
}
declare module 'relay-test-utils/lib/RelayTestSchema.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/RelayTestSchema'>;
}
declare module 'relay-test-utils/lib/RelayTestSchemaPath.js' {
  declare module.exports: $Exports<'relay-test-utils/lib/RelayTestSchemaPath'>;
}
declare module 'relay-test-utils/relay-test-utils.js' {
  declare module.exports: $Exports<'relay-test-utils/relay-test-utils'>;
}
declare module 'relay-test-utils/relay-test-utils.min.js' {
  declare module.exports: $Exports<'relay-test-utils/relay-test-utils.min'>;
}
