// flow-typed signature: d59bf98b8d9346310bf3cf6b7c81960e
// flow-typed version: <<STUB>>/renamer_v^1.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'renamer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'renamer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'renamer/bin/cli' {
  declare module.exports: any;
}

declare module 'renamer/lib/cli-app' {
  declare module.exports: any;
}

declare module 'renamer/lib/cli-options' {
  declare module.exports: any;
}

declare module 'renamer/lib/plugin-base' {
  declare module.exports: any;
}

declare module 'renamer/lib/plugin/default' {
  declare module.exports: any;
}

declare module 'renamer/lib/plugin/index' {
  declare module.exports: any;
}

declare module 'renamer/lib/rename-file' {
  declare module.exports: any;
}

declare module 'renamer/lib/replacer' {
  declare module.exports: any;
}

declare module 'renamer/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'renamer/bin/cli.js' {
  declare module.exports: $Exports<'renamer/bin/cli'>;
}
declare module 'renamer/index' {
  declare module.exports: $Exports<'renamer'>;
}
declare module 'renamer/index.js' {
  declare module.exports: $Exports<'renamer'>;
}
declare module 'renamer/lib/cli-app.js' {
  declare module.exports: $Exports<'renamer/lib/cli-app'>;
}
declare module 'renamer/lib/cli-options.js' {
  declare module.exports: $Exports<'renamer/lib/cli-options'>;
}
declare module 'renamer/lib/plugin-base.js' {
  declare module.exports: $Exports<'renamer/lib/plugin-base'>;
}
declare module 'renamer/lib/plugin/default.js' {
  declare module.exports: $Exports<'renamer/lib/plugin/default'>;
}
declare module 'renamer/lib/plugin/index.js' {
  declare module.exports: $Exports<'renamer/lib/plugin/index'>;
}
declare module 'renamer/lib/rename-file.js' {
  declare module.exports: $Exports<'renamer/lib/rename-file'>;
}
declare module 'renamer/lib/replacer.js' {
  declare module.exports: $Exports<'renamer/lib/replacer'>;
}
declare module 'renamer/lib/util.js' {
  declare module.exports: $Exports<'renamer/lib/util'>;
}
