// flow-typed signature: 1a3c1bc045a864ee01b8af69c1c69256
// flow-typed version: <<STUB>>/tabletop_v^1.5.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tabletop'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tabletop' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tabletop/examples/backbone/backbone' {
  declare module.exports: any;
}

declare module 'tabletop/examples/common/jquery' {
  declare module.exports: any;
}

declare module 'tabletop/examples/common/underscore' {
  declare module.exports: any;
}

declare module 'tabletop/examples/handlebars/handlebars' {
  declare module.exports: any;
}

declare module 'tabletop/examples/nodejs/test' {
  declare module.exports: any;
}

declare module 'tabletop/Gruntfile' {
  declare module.exports: any;
}

declare module 'tabletop/src/backbone.tabletopSync' {
  declare module.exports: any;
}

declare module 'tabletop/src/tabletop' {
  declare module.exports: any;
}

declare module 'tabletop/src/tabletop.min' {
  declare module.exports: any;
}

declare module 'tabletop/test/sheets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tabletop/examples/backbone/backbone.js' {
  declare module.exports: $Exports<'tabletop/examples/backbone/backbone'>;
}
declare module 'tabletop/examples/common/jquery.js' {
  declare module.exports: $Exports<'tabletop/examples/common/jquery'>;
}
declare module 'tabletop/examples/common/underscore.js' {
  declare module.exports: $Exports<'tabletop/examples/common/underscore'>;
}
declare module 'tabletop/examples/handlebars/handlebars.js' {
  declare module.exports: $Exports<'tabletop/examples/handlebars/handlebars'>;
}
declare module 'tabletop/examples/nodejs/test.js' {
  declare module.exports: $Exports<'tabletop/examples/nodejs/test'>;
}
declare module 'tabletop/Gruntfile.js' {
  declare module.exports: $Exports<'tabletop/Gruntfile'>;
}
declare module 'tabletop/src/backbone.tabletopSync.js' {
  declare module.exports: $Exports<'tabletop/src/backbone.tabletopSync'>;
}
declare module 'tabletop/src/tabletop.js' {
  declare module.exports: $Exports<'tabletop/src/tabletop'>;
}
declare module 'tabletop/src/tabletop.min.js' {
  declare module.exports: $Exports<'tabletop/src/tabletop.min'>;
}
declare module 'tabletop/test/sheets.js' {
  declare module.exports: $Exports<'tabletop/test/sheets'>;
}
