// @flow strict
import getCallingCodes from "../getCallingCodes";

const countries = {
  ad: {
    id: "ad",
    currency: "eur",
    continent: "eu",
    AR: "أندورا",
    BG: "Андора",
    BR: "Andorra",
    CA: "Andorra",
    CN: "安道尔",
    CS: "Andorra",
    DA: "Andorra",
    DE: "Andorra",
    EL: "Ανδόρα",
    EN: "Andorra",
    ES: "Andorra",
    FI: "Andorra",
    FR: "Andorre",
    HR: "Andora",
    HU: "Andorra",
    ID: "Andora",
    IE: "Andorra",
    IS: "Andorra",
    IT: "Andorra",
    JA: "アンドラ",
    KO: "안도라",
    LT: "Andora",
    MX: "Andorra",
    NL: "Andorra",
    NO: "Andorra",
    NZ: "Andorra",
    PL: "Andora",
    PT: "Andorra",
    RO: "Andorra",
    RU: "Андорра",
    SK: "Andorra",
    SR: "Andora",
    SV: "Andorra",
    TH: "อันดอร์รา",
    TR: "Andorra",
    TW: "安道尔",
    UK: "Андорра",
    VN: "Andorra",
    HE: "אנדורה",
    slug: "andorra",
    callingCode: "376",
  },
  ae: {
    id: "ae",
    currency: "aed",
    continent: "mea",
    AR: "الامارات العربية المتحدة",
    BG: "Обединени арабски емирства",
    BR: "Emirados Árabes Unidos",
    CA: "Unió dels Emirats Àrabs",
    CN: "阿拉伯联合酋长国",
    CS: "Spojené arabské emiráty",
    DA: "Forenede Arabiske Emirater",
    DE: "Vereinigte Arabische Emirate",
    EL: "Ηνωμένα Αραβικά Εμιράτα",
    EN: "United Arab Emirates",
    ES: "Emiratos Árabes Unidos",
    FI: "Arabiemiirikunnat",
    FR: "Émirats arabes unis",
    HR: "Ujedinjeni Arapski Emirati",
    HU: "Egyesült Arab Emirátus",
    ID: "Uni Emirat Arab",
    IE: "United Arab Emirates",
    IS: "Sameinuðu arabísku furstadæmin",
    IT: "Emirati Arabi Uniti",
    JA: "アラブ首長国連邦",
    KO: "아랍에미리트 연합",
    LT: "Jungtiniai Arabų Emyratai",
    MX: "Emiratos Árabes Unidos",
    NL: "Verenigde Arabische Emiraten",
    NO: "De forente arabiske emirater",
    NZ: "United Arab Emirates",
    PL: "Zjednoczone Emiraty Arabskie",
    PT: "Emirados Árabes Unidos",
    RO: "Emiratele Arabe Unite",
    RU: "Объединенные Арабские Эмираты",
    SK: "Spojené arabské emiráty",
    SR: "Ujedinjeni Arapski Emirati",
    SV: "Förenade Arabemiraten",
    TH: "สหรัฐอาหรับเอมิเรตส์",
    TR: "Birleşik Arap Emirlikleri",
    TW: "阿拉伯联合酋长国",
    UK: "Обʼєднані Арабські Емірати",
    VN: "Các Tiểu Vương quốc A-rập Thống nhất",
    HE: "איחוד האמירויות הערביות",
    slug: "united-arab-emirates",
    callingCode: "971",
  },
};

describe("#getCallingCode", () => {
  it("should get value and label", () => {
    expect(getCallingCodes(countries, "EN")).toEqual([
      { label: "Andorra", value: "376" },
      { label: "United Arab Emirates", value: "971" },
    ]);
  });
});
