// @flow strict
// FIXME use these in 'InitAuth' - not used on FE currently so we're good
// export const AUTH_FORGOT_REQUEST = "AUTH_FORGOT_REQUEST";
// export const AUTH_FORGOT_ERROR = "AUTH_FORGOT_ERROR";
// export const AUTH_FORGOT_SUCCESS = "AUTH_FORGOT_SUCCESS";
// export const AUTH_PASSWORD_RESET_SUCCESS = "AUTH_PASSWORD_RESET_SUCCESS";
// export const AUTH_PASSWORD_RESET_ERROR_INVALID_NEW_PASSWORD =
//   "AUTH_PASSWORD_RESET_ERROR_INVALID_NEW_PASSWORD";
// export const AUTH_PASSWORD_RESET_ERROR_INVALID_TOKEN = "AUTH_PASSWORD_RESET_ERROR_INVALID_TOKEN";
// export const AUTH_PASSWORD_RESET_ERROR_UNKNOWN = "AUTH_PASSWORD_RESET_ERROR_UNKNOWN";
// export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
// export const AUTH_PASSWORD_VERIFY_REQUEST = "AUTH_PASSWORD_VERIFY_REQUEST";
// export const AUTH_PASSWORD_VERIFY_SUCCESS = "AUTH_PASSWORD_VERIFY_SUCCESS";
// export const AUTH_PASSWORD_VERIFY_ERROR = "AUTH_PASSWORD_VERIFY_ERROR";
// export const AUTH_LOGIN_WITH_PASSWORD_REQUEST = "AUTH_LOGIN_WITH_PASSWORD_REQUEST";
// export const AUTH_LOGIN_WITH_BOOKING_GETTING_TOKEN = "AUTH_LOGIN_WITH_BOOKING_GETTING_TOKEN";
// export const AUTH_LOGIN_WITH_BOOKING_GETTING_TOKEN_ERROR =
//   "AUTH_LOGIN_WITH_BOOKING_GETTING_TOKEN_ERROR";
// export const AUTH_LOGIN_WITH_BOOKING_GETTING_TOKEN_SUCCESS =
//   "AUTH_LOGIN_WITH_BOOKING_GETTING_TOKEN_SUCCESS";
// export const AUTH_LOGIN_WITH_BOOKING_GETTING_IATA_ERROR =
//   "AUTH_LOGIN_WITH_BOOKING_GETTING_IATA_ERROR";
// export const AUTH_LOGIN_ERROR_RETRIEVING_USER = "AUTH_LOGIN_ERROR_RETRIEVING_USER";
// export const AUTH_LOGIN_OAUTH_REDIRECT_ERROR = "AUTH_LOGIN_OAUTH_REDIRECT_ERROR";
// export const AUTH_LOGIN_WITH_AUTH_TOKEN = "AUTH_LOGIN_WITH_AUTH_TOKEN";
// export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const OPEN_MODAL = "OPEN_MODAL";
export const OPEN_CHAT = "OPEN_CHAT";
export const OPEN_CURRENCY = "OPEN_CURRENCY";

export const API_REQUEST = "API_REQUEST";
export const API_FAIL = "API_FAIL";
export const API_SUCCESS = "API_SUCCESS";
