// flow-typed signature: 35df0d6dd0a8aebced9818c8fdb93f9c
// flow-typed version: <<STUB>>/@storybook/components_v5.0.3/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/components/dist/ActionBar/ActionBar' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/ActionBar/ActionBar.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Badge/Badge' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Badge/Badge.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/bar/bar' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/bar/button' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/bar/separator' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookIcon' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookIcon.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookLogo' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/brand/StorybookLogo.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Button/Button' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/Button/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/field/field' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/form.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/index' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/form/input/input' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/icon' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/icon.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/icons' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/icon/svg' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/placeholder/placeholder' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/placeholder/placeholder.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/spaced/Spaced' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/spaced/Spaced.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/StoryLinkWrapper' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tabs/tabs' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tabs/tabs.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/ListItem' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/ListItem.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/Tooltip.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipLinkList' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipLinkList.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipMessage' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipMessage.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipNote' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/TooltipNote.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/WithTooltip' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/tooltip/WithTooltip.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/DocumentFormatting' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/DocumentFormatting.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/link/link' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/link/link.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/link/link.test' {
  declare module.exports: any;
}

declare module '@storybook/components/dist/typography/typography.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/ActionBar/ActionBar' {
  declare module.exports: any;
}

declare module '@storybook/components/src/ActionBar/ActionBar.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/Badge/Badge' {
  declare module.exports: any;
}

declare module '@storybook/components/src/Badge/Badge.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/bar/bar' {
  declare module.exports: any;
}

declare module '@storybook/components/src/bar/button' {
  declare module.exports: any;
}

declare module '@storybook/components/src/bar/separator' {
  declare module.exports: any;
}

declare module '@storybook/components/src/brand/StorybookIcon' {
  declare module.exports: any;
}

declare module '@storybook/components/src/brand/StorybookIcon.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/brand/StorybookLogo' {
  declare module.exports: any;
}

declare module '@storybook/components/src/brand/StorybookLogo.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/Button/Button' {
  declare module.exports: any;
}

declare module '@storybook/components/src/Button/Button.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/field/field' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/form.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/index' {
  declare module.exports: any;
}

declare module '@storybook/components/src/form/input/input' {
  declare module.exports: any;
}

declare module '@storybook/components/src/icon/icon' {
  declare module.exports: any;
}

declare module '@storybook/components/src/icon/icon.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/icon/icons' {
  declare module.exports: any;
}

declare module '@storybook/components/src/icon/svg' {
  declare module.exports: any;
}

declare module '@storybook/components/src/index' {
  declare module.exports: any;
}

declare module '@storybook/components/src/placeholder/placeholder' {
  declare module.exports: any;
}

declare module '@storybook/components/src/placeholder/placeholder.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/spaced/Spaced' {
  declare module.exports: any;
}

declare module '@storybook/components/src/spaced/Spaced.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/StoryLinkWrapper' {
  declare module.exports: any;
}

declare module '@storybook/components/src/syntaxhighlighter/syntaxhighlighter' {
  declare module.exports: any;
}

declare module '@storybook/components/src/syntaxhighlighter/syntaxhighlighter.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tabs/tabs' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tabs/tabs.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/ListItem' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/ListItem.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/Tooltip' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/Tooltip.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/TooltipLinkList' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/TooltipLinkList.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/TooltipMessage' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/TooltipMessage.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/TooltipNote' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/TooltipNote.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/WithTooltip' {
  declare module.exports: any;
}

declare module '@storybook/components/src/tooltip/WithTooltip.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/typography/DocumentFormatting' {
  declare module.exports: any;
}

declare module '@storybook/components/src/typography/DocumentFormatting.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/typography/link/link' {
  declare module.exports: any;
}

declare module '@storybook/components/src/typography/link/link.stories' {
  declare module.exports: any;
}

declare module '@storybook/components/src/typography/link/link.test' {
  declare module.exports: any;
}

declare module '@storybook/components/src/typography/typography.stories' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/components/dist/ActionBar/ActionBar.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ActionBar/ActionBar'>;
}
declare module '@storybook/components/dist/ActionBar/ActionBar.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/ActionBar/ActionBar.stories'>;
}
declare module '@storybook/components/dist/Badge/Badge.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Badge/Badge'>;
}
declare module '@storybook/components/dist/Badge/Badge.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Badge/Badge.stories'>;
}
declare module '@storybook/components/dist/bar/bar.js' {
  declare module.exports: $Exports<'@storybook/components/dist/bar/bar'>;
}
declare module '@storybook/components/dist/bar/button.js' {
  declare module.exports: $Exports<'@storybook/components/dist/bar/button'>;
}
declare module '@storybook/components/dist/bar/separator.js' {
  declare module.exports: $Exports<'@storybook/components/dist/bar/separator'>;
}
declare module '@storybook/components/dist/brand/StorybookIcon.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookIcon'>;
}
declare module '@storybook/components/dist/brand/StorybookIcon.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookIcon.stories'>;
}
declare module '@storybook/components/dist/brand/StorybookLogo.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookLogo'>;
}
declare module '@storybook/components/dist/brand/StorybookLogo.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/brand/StorybookLogo.stories'>;
}
declare module '@storybook/components/dist/Button/Button.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Button/Button'>;
}
declare module '@storybook/components/dist/Button/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/Button/Button.stories'>;
}
declare module '@storybook/components/dist/form/field/field.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/field/field'>;
}
declare module '@storybook/components/dist/form/form.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/form.stories'>;
}
declare module '@storybook/components/dist/form/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/index'>;
}
declare module '@storybook/components/dist/form/input/input.js' {
  declare module.exports: $Exports<'@storybook/components/dist/form/input/input'>;
}
declare module '@storybook/components/dist/icon/icon.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/icon'>;
}
declare module '@storybook/components/dist/icon/icon.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/icon.stories'>;
}
declare module '@storybook/components/dist/icon/icons.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/icons'>;
}
declare module '@storybook/components/dist/icon/svg.js' {
  declare module.exports: $Exports<'@storybook/components/dist/icon/svg'>;
}
declare module '@storybook/components/dist/index.js' {
  declare module.exports: $Exports<'@storybook/components/dist/index'>;
}
declare module '@storybook/components/dist/placeholder/placeholder.js' {
  declare module.exports: $Exports<'@storybook/components/dist/placeholder/placeholder'>;
}
declare module '@storybook/components/dist/placeholder/placeholder.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/placeholder/placeholder.stories'>;
}
declare module '@storybook/components/dist/spaced/Spaced.js' {
  declare module.exports: $Exports<'@storybook/components/dist/spaced/Spaced'>;
}
declare module '@storybook/components/dist/spaced/Spaced.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/spaced/Spaced.stories'>;
}
declare module '@storybook/components/dist/StoryLinkWrapper.js' {
  declare module.exports: $Exports<'@storybook/components/dist/StoryLinkWrapper'>;
}
declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.js' {
  declare module.exports: $Exports<'@storybook/components/dist/syntaxhighlighter/syntaxhighlighter'>;
}
declare module '@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories'>;
}
declare module '@storybook/components/dist/tabs/tabs.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tabs/tabs'>;
}
declare module '@storybook/components/dist/tabs/tabs.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tabs/tabs.stories'>;
}
declare module '@storybook/components/dist/tooltip/ListItem.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/ListItem'>;
}
declare module '@storybook/components/dist/tooltip/ListItem.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/ListItem.stories'>;
}
declare module '@storybook/components/dist/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/Tooltip'>;
}
declare module '@storybook/components/dist/tooltip/Tooltip.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/Tooltip.stories'>;
}
declare module '@storybook/components/dist/tooltip/TooltipLinkList.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipLinkList'>;
}
declare module '@storybook/components/dist/tooltip/TooltipLinkList.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipLinkList.stories'>;
}
declare module '@storybook/components/dist/tooltip/TooltipMessage.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipMessage'>;
}
declare module '@storybook/components/dist/tooltip/TooltipMessage.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipMessage.stories'>;
}
declare module '@storybook/components/dist/tooltip/TooltipNote.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipNote'>;
}
declare module '@storybook/components/dist/tooltip/TooltipNote.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/TooltipNote.stories'>;
}
declare module '@storybook/components/dist/tooltip/WithTooltip.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/WithTooltip'>;
}
declare module '@storybook/components/dist/tooltip/WithTooltip.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/tooltip/WithTooltip.stories'>;
}
declare module '@storybook/components/dist/typography/DocumentFormatting.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/DocumentFormatting'>;
}
declare module '@storybook/components/dist/typography/DocumentFormatting.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/DocumentFormatting.stories'>;
}
declare module '@storybook/components/dist/typography/link/link.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/link/link'>;
}
declare module '@storybook/components/dist/typography/link/link.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/link/link.stories'>;
}
declare module '@storybook/components/dist/typography/link/link.test.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/link/link.test'>;
}
declare module '@storybook/components/dist/typography/typography.stories.js' {
  declare module.exports: $Exports<'@storybook/components/dist/typography/typography.stories'>;
}
declare module '@storybook/components/src/ActionBar/ActionBar.js' {
  declare module.exports: $Exports<'@storybook/components/src/ActionBar/ActionBar'>;
}
declare module '@storybook/components/src/ActionBar/ActionBar.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/ActionBar/ActionBar.stories'>;
}
declare module '@storybook/components/src/Badge/Badge.js' {
  declare module.exports: $Exports<'@storybook/components/src/Badge/Badge'>;
}
declare module '@storybook/components/src/Badge/Badge.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/Badge/Badge.stories'>;
}
declare module '@storybook/components/src/bar/bar.js' {
  declare module.exports: $Exports<'@storybook/components/src/bar/bar'>;
}
declare module '@storybook/components/src/bar/button.js' {
  declare module.exports: $Exports<'@storybook/components/src/bar/button'>;
}
declare module '@storybook/components/src/bar/separator.js' {
  declare module.exports: $Exports<'@storybook/components/src/bar/separator'>;
}
declare module '@storybook/components/src/brand/StorybookIcon.js' {
  declare module.exports: $Exports<'@storybook/components/src/brand/StorybookIcon'>;
}
declare module '@storybook/components/src/brand/StorybookIcon.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/brand/StorybookIcon.stories'>;
}
declare module '@storybook/components/src/brand/StorybookLogo.js' {
  declare module.exports: $Exports<'@storybook/components/src/brand/StorybookLogo'>;
}
declare module '@storybook/components/src/brand/StorybookLogo.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/brand/StorybookLogo.stories'>;
}
declare module '@storybook/components/src/Button/Button.js' {
  declare module.exports: $Exports<'@storybook/components/src/Button/Button'>;
}
declare module '@storybook/components/src/Button/Button.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/Button/Button.stories'>;
}
declare module '@storybook/components/src/form/field/field.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/field/field'>;
}
declare module '@storybook/components/src/form/form.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/form.stories'>;
}
declare module '@storybook/components/src/form/index.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/index'>;
}
declare module '@storybook/components/src/form/input/input.js' {
  declare module.exports: $Exports<'@storybook/components/src/form/input/input'>;
}
declare module '@storybook/components/src/icon/icon.js' {
  declare module.exports: $Exports<'@storybook/components/src/icon/icon'>;
}
declare module '@storybook/components/src/icon/icon.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/icon/icon.stories'>;
}
declare module '@storybook/components/src/icon/icons.js' {
  declare module.exports: $Exports<'@storybook/components/src/icon/icons'>;
}
declare module '@storybook/components/src/icon/svg.js' {
  declare module.exports: $Exports<'@storybook/components/src/icon/svg'>;
}
declare module '@storybook/components/src/index.js' {
  declare module.exports: $Exports<'@storybook/components/src/index'>;
}
declare module '@storybook/components/src/placeholder/placeholder.js' {
  declare module.exports: $Exports<'@storybook/components/src/placeholder/placeholder'>;
}
declare module '@storybook/components/src/placeholder/placeholder.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/placeholder/placeholder.stories'>;
}
declare module '@storybook/components/src/spaced/Spaced.js' {
  declare module.exports: $Exports<'@storybook/components/src/spaced/Spaced'>;
}
declare module '@storybook/components/src/spaced/Spaced.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/spaced/Spaced.stories'>;
}
declare module '@storybook/components/src/StoryLinkWrapper.js' {
  declare module.exports: $Exports<'@storybook/components/src/StoryLinkWrapper'>;
}
declare module '@storybook/components/src/syntaxhighlighter/syntaxhighlighter.js' {
  declare module.exports: $Exports<'@storybook/components/src/syntaxhighlighter/syntaxhighlighter'>;
}
declare module '@storybook/components/src/syntaxhighlighter/syntaxhighlighter.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/syntaxhighlighter/syntaxhighlighter.stories'>;
}
declare module '@storybook/components/src/tabs/tabs.js' {
  declare module.exports: $Exports<'@storybook/components/src/tabs/tabs'>;
}
declare module '@storybook/components/src/tabs/tabs.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tabs/tabs.stories'>;
}
declare module '@storybook/components/src/tooltip/ListItem.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/ListItem'>;
}
declare module '@storybook/components/src/tooltip/ListItem.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/ListItem.stories'>;
}
declare module '@storybook/components/src/tooltip/Tooltip.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/Tooltip'>;
}
declare module '@storybook/components/src/tooltip/Tooltip.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/Tooltip.stories'>;
}
declare module '@storybook/components/src/tooltip/TooltipLinkList.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/TooltipLinkList'>;
}
declare module '@storybook/components/src/tooltip/TooltipLinkList.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/TooltipLinkList.stories'>;
}
declare module '@storybook/components/src/tooltip/TooltipMessage.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/TooltipMessage'>;
}
declare module '@storybook/components/src/tooltip/TooltipMessage.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/TooltipMessage.stories'>;
}
declare module '@storybook/components/src/tooltip/TooltipNote.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/TooltipNote'>;
}
declare module '@storybook/components/src/tooltip/TooltipNote.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/TooltipNote.stories'>;
}
declare module '@storybook/components/src/tooltip/WithTooltip.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/WithTooltip'>;
}
declare module '@storybook/components/src/tooltip/WithTooltip.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/tooltip/WithTooltip.stories'>;
}
declare module '@storybook/components/src/typography/DocumentFormatting.js' {
  declare module.exports: $Exports<'@storybook/components/src/typography/DocumentFormatting'>;
}
declare module '@storybook/components/src/typography/DocumentFormatting.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/typography/DocumentFormatting.stories'>;
}
declare module '@storybook/components/src/typography/link/link.js' {
  declare module.exports: $Exports<'@storybook/components/src/typography/link/link'>;
}
declare module '@storybook/components/src/typography/link/link.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/typography/link/link.stories'>;
}
declare module '@storybook/components/src/typography/link/link.test.js' {
  declare module.exports: $Exports<'@storybook/components/src/typography/link/link.test'>;
}
declare module '@storybook/components/src/typography/typography.stories.js' {
  declare module.exports: $Exports<'@storybook/components/src/typography/typography.stories'>;
}
